config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  get 'products/predict'
  resources :products
  get 'top' => 'home#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :price, numericality: {only_integer: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :redirect_root

  def index
    @product = Product.new
    @user = current_user
    @products = @user.products
    @total_price = @products.sum(:price)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @total_price = params[:total_price].to_i + @product.price
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    redirect_to root_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to root_path
  end

  def predict
    @products = Product.where('evaluation >= ?', 4)
    @predict_price = @products.sum(:price)
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :maker_name, :note, :evaluation).merge(user_id: current_user.id)
  end

  def redirect_root
    redirect_to top_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/top.html.erb
<head>
<title>Wantest</title>
</head>

<body>
  <nav class="nav">
    <div class="header">
      <h2 class="headerli0"><i class="fa-solid fa-money-check-dollar fa-lg"></i></i> Wantest</h2>
      <p class="headerli1"><span><%= link_to 'Wantestを使ってみる', new_user_registration_path, class:"innerheaderli1" %></span></p>
      <a href="/users/sign_in" class="innerheaderli2"><i class="fa-solid fa-right-to-bracket"></i>ログイン</a>
    </div> 
  </nav>
  <main class="topmain">
    <h1>自分の欲しいもの整理してみませんか？</h1>
    <h3>整理した情報をもとに支出予測が立てられます。</h3>
    <p class="topmainp"><span><%= link_to 'Wantestを使ってみる', new_user_registration_path, class:"innerheaderli1" %></span></p>
    <img src="/packs/media/images/%202022-07-04-8c3448251d76ae673ad329cd2a3c6839.png" class="topphoto">
    <p>商品を登録して一覧で見られるようになります。</p>
  </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWantApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/css/bootstrap.css">
  </head>

  <body class="container">
    <%# if flash[:notice] %>
      <%# <div class="alert alert-info"> %>
        <%#= flash[:notice] %>
      <%# </div> %>
    <%# end %>
    <%# if flash[:alert] %>
      <%# <div class="alert alert-danger"> %>
        <%#= flash[:alert] %>
      <%# </div> %>
    <%# end %>
    <%= yield %>
  </body>
</html>

app/views/products/_products1.html.erb
<% if product.evaluation == 1 %>
  <div class="card-body">
    <h3 class="card-title"><%= product.name %></h3>
    <h3 class="card-subtitle"><%= number_to_currency(product.price, unit: "¥", precision: 0) %></h3>
    <h4 class = "star-eva">★☆☆☆☆</h4>
    <p class="editpointer" id="edit_<%= product.id %>"><i class="fa-solid fa-pen-to-square"></i>編集</p>
    <p><i class="fa-solid fa-trash"></i><%= link_to '削除', product_path(product.id), method: :delete, local: true %></p>
  </div>

  <div class="modal" id="modal_<%= product.id %>">
    <h1 class="display-4 text-primary">商品情報編集</h1>
    <%= form_with model: product, url: product_path(product.id), method: :patch, data: {local: true} do |f| %>
      <div class="form-group"> 
        <label for="name" class="textbox">商品名</label>
        <%= f.text_field :name, class:"form-control", id:"productn_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <label for="price" class="textbox">金額</label>
        <%= f.number_field :price, min:0, class:"form-control", id:"productp_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <label for="note" class="textbox">メモ</label>
        <%= f.text_field :note, class:"form-control", id:"productno_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <%= f.hidden_field :evaluation, :value => product.evaluation , class:"form-control", id:"hidden_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <%= f.submit "更新", class: "btn btn-primary" %>
      </div>
    <% end %>
    
    <div class="review-stars">
      <div id="star-1_<%= product.id %>" class="true">
        <% if product.evaluation >= 1%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-2_<%= product.id %>" class="">
        <% if product.evaluation >= 2%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-3_<%= product.id %>" class="">
        <% if product.evaluation >= 3%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-4_<%= product.id %>" class="">
        <% if product.evaluation >= 4%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-5_<%= product.id %>" class="">
        <% if product.evaluation >= 5%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
    </div>
  </div>


  <div class="mask" id="mask_<%= product.id %>"></div>
  <script>
  var modal_edit<%= product.id %> = document.getElementById("modal_<%= product.id %>")
  var edit<%= product.id %> = document.getElementById("edit_<%= product.id %>")
  var mask<%= product.id %> = document.getElementById("mask_<%= product.id %>")
  edit<%= product.id %>.addEventListener('click', function() {
    modal_edit<%= product.id %>.style.display = 'block';
    mask<%= product.id %>.style.display = 'block';
  });
  mask<%= product.id %>.addEventListener('click', function() {
    modal_edit<%= product.id %>.style.display = 'none';
    mask<%= product.id %>.style.display = 'none';
  });

  const star1<%= product.id %> = document.getElementById("star-1_<%= product.id %>");
  const star2<%= product.id %> = document.getElementById("star-2_<%= product.id %>");
  const star3<%= product.id %> = document.getElementById("star-3_<%= product.id %>");
  const star4<%= product.id %> = document.getElementById("star-4_<%= product.id %>");
  const star5<%= product.id %> = document.getElementById("star-5_<%= product.id %>");
  star1<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "☆"
      star3<%= product.id %>.innerHTML = "☆"
      star4<%= product.id %>.innerHTML = "☆"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.add('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "1"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star2<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "☆"
      star4<%= product.id %>.innerHTML = "☆"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.add('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "2"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star3<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "★"
      star4<%= product.id %>.innerHTML = "☆"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.add('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "3"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star4<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "★"
      star4<%= product.id %>.innerHTML = "★"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.add('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "4"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star5<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "★"
      star4<%= product.id %>.innerHTML = "★"
      star5<%= product.id %>.innerHTML = "★"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.add('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "5"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  </script>
<% end %>
  

app/views/products/_products2.html.erb
<% if product.evaluation == 2 %>
  <div class="card-body">
    <h3 class="card-title"><%= product.name %></h3>
    <h3 class="card-subtitle"><%= number_to_currency(product.price, unit: "¥", precision: 0) %></h3>
    <h4 class = "star-eva">★★☆☆☆</h4>
    <p class="editpointer" id="edit_<%= product.id %>"><i class="fa-solid fa-pen-to-square"></i>編集</p>
    <p><i class="fa-solid fa-trash"></i><%= link_to '削除', product_path(product.id), method: :delete, local: true %></p>
  </div>

  <div class="modal" id="modal_<%= product.id %>">
    <h1 class="display-4 text-primary">商品情報編集</h1>
    <%= form_with model: product, url: product_path(product.id), method: :patch, data: {local: true} do |f| %>
      <div class="form-group"> 
        <label for="name" class="textbox">商品名</label>
        <%= f.text_field :name, class:"form-control", id:"productn_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <label for="price" class="textbox">金額</label>
        <%= f.number_field :price, min:0, class:"form-control", id:"productp_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <label for="note" class="textbox">メモ</label>
        <%= f.text_field :note, class:"form-control", id:"productno_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <%= f.hidden_field :evaluation, :value => product.evaluation , class:"form-control", id:"hidden_#{product.id}" %>
      </div>
      <div class="form-group"> 
        <%= f.submit "更新", class: "btn btn-primary" %>
      </div>
    <% end %>
    
    <div class="review-stars">
      <div id="star-1_<%= product.id %>" class="true">
        <% if product.evaluation >= 1%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-2_<%= product.id %>" class="">
        <% if product.evaluation >= 2%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-3_<%= product.id %>" class="">
        <% if product.evaluation >= 3%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-4_<%= product.id %>" class="">
        <% if product.evaluation >= 4%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
      <div id="star-5_<%= product.id %>" class="">
        <% if product.evaluation >= 5%>
          ★
        <% else %>
          ☆
        <% end %>
      </div>
    </div>
  </div>


  <div class="mask" id="mask_<%= product.id %>"></div>
  <script>
  var modal_edit<%= product.id %> = document.getElementById("modal_<%= product.id %>")
  var edit<%= product.id %> = document.getElementById("edit_<%= product.id %>")
  var mask<%= product.id %> = document.getElementById("mask_<%= product.id %>")
  edit<%= product.id %>.addEventListener('click', function() {
    modal_edit<%= product.id %>.style.display = 'block';
    mask<%= product.id %>.style.display = 'block';
  });
  mask<%= product.id %>.addEventListener('click', function() {
    modal_edit<%= product.id %>.style.display = 'none';
    mask<%= product.id %>.style.display = 'none';
  });

  const star1<%= product.id %> = document.getElementById("star-1_<%= product.id %>");
  const star2<%= product.id %> = document.getElementById("star-2_<%= product.id %>");
  const star3<%= product.id %> = document.getElementById("star-3_<%= product.id %>");
  const star4<%= product.id %> = document.getElementById("star-4_<%= product.id %>");
  const star5<%= product.id %> = document.getElementById("star-5_<%= product.id %>");
  star1<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "☆"
      star3<%= product.id %>.innerHTML = "☆"
      star4<%= product.id %>.innerHTML = "☆"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.add('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "1"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star2<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "☆"
      star4<%= product.id %>.innerHTML = "☆"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.add('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "2"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star3<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "★"
      star4<%= product.id %>.innerHTML = "☆"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.add('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "3"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star4<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "★"
      star4<%= product.id %>.innerHTML = "★"
      star5<%= product.id %>.innerHTML = "☆"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.add('true')
      star5<%= product.id %>.classList.remove('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "4"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  star5<%= product.id %>.addEventListener('click', function () {
      star1<%= product.id %>.innerHTML = "★"
      star2<%= product.id %>.innerHTML = "★"
      star3<%= product.id %>.innerHTML = "★"
      star4<%= product.id %>.innerHTML = "★"
      star5<%= product.id %>.innerHTML = "★"
      star1<%= product.id %>.classList.remove('true')
      star2<%= product.id %>.classList.remove('true')
      star3<%= product.id %>.classList.remove('true')
      star4<%= product.id %>.classList.remove('true')
      star5<%= product.id %>.classList.add('true')
      document.getElementById("hidden_<%= product.id %>")
      console.log(document.getElementById("hidden_<%= product.id %>").value)
      document.getElementById("hidden_<%= product.id %>").value = "5"
      console.log(document.getElementById("hidden_<%= product.id %>").value)
  });
  </script>
<% end %>

app/views/products/index.html.erb
<h1 class="explanation">商品登録画面</h1>
<p class="explanation">「+新規登録」ボタンをクリックすると、商品の登録ができます。</p>
<p class="explanation">商品名、金額を入力し、5段階で自分の購入意欲度に合わせて星の部分をクリックして「登録」ボタンを押してください。(メモ欄は自由にお使いください)</p>

<div class="sum-price" id="sum-price"> 
  <label>合計金額 </label><span>¥</span><span id="sumprice"><%= @total_price.to_s(:delimited) %></span>
</div>

<div class="topper">
  <button id="btn"><i class="fa-solid fa-square-plus"></i>新規作成</button>
  <% if user_signed_in? %>
    <%= link_to(destroy_user_session_path, method: :delete, class:"signoutbox1") do %>
      <p class="signoutbox">サインアウト<i class="fa-solid fa-right-from-bracket"></i><p>
    <% end %>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div id="evaluation_5">
      <% @products.each do |product| %> 
        <%= render '/products/products5', product: product %>
      <% end %>
    </div>
    <div id="evaluation_4">
      <% @products.each do |product| %>
        <%= render '/products/products4', product: product %>
      <% end %>
    </div>
    <div id="evaluation_3">
      <% @products.each do |product| %>
        <%= render '/products/products3', product: product %>
      <% end %>
    </div>
    <div id="evaluation_2">
      <% @products.each do |product| %>
        <%= render '/products/products2', product: product %>
      <% end %>
    </div>
    <div id="evaluation_1">
      <% @products.each do |product| %>
        <%= render '/products/products1', product: product %>
      <% end %>
    </div>
  </div>
</div>

<%# <p><%= link_to '予測画面', products_predict_path, class: "btn btn-success" %>


<div class="modal" id="modal-new">
  <h1 class="display-4 text-primary" id="mylist">商品登録</h1>
      <%= form_with model: Product.new, url: products_path(total_price: @total_price), id: 'products_create_form',  method: :post, data: {remote: true} do |f| %>
        <div class="form-group"> 
          <label for="name" class="textbox">商品名</label>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group"> 
          <label for="price" class="textbox">金額</label>
          <%= f.number_field :price, min:0, class:"form-control" %>
        </div>
        <div class="form-group"> 
          <label for="note" class="textbox">メモ</label>
          <%= f.text_field :note, class:"form-control" %>
        </div>
        <div class="form-group"> 
          <%= f.hidden_field :evaluation, :value => "1" , class:"form-control", id:"sugie" %>
        </div>

        <div class="form-group" id="submit"> 
          <%= f.submit "登録", class: "btn btn-primary" %>
        </div> 

      <% end %>

      <div id="star-all" class="review-stars">
        <div id="star-1" class="true">
          ★
        </div>
        <div id="star-2" class="">
          ☆
        </div>
        <div id="star-3" class="">
          ☆
        </div>
        <div id="star-4" class="">
          ☆
        </div>
        <div id="star-5" class="">
          ☆
        </div>
      </div>
      <%= javascript_pack_tag 'new' %>
</div>

<div class="mask" id="mask"></div>

<script>
var btn = document.getElementById('btn')
var mask = document.getElementById('mask')
var modal = document.getElementById('modal-new')

btn.addEventListener('click', function() {
  modal.style.display = 'block';
  mask.style.display = 'block';
})
mask.addEventListener('click', function() {
  modal.style.display = 'none';
  mask.style.display = 'none';
})
var products_create = document.getElementById("products_create_form")
console.log("uuu", products_create.action);
</script>

app/views/products/predict.html.erb
<h1 class="display-4 text-primary">支出予測</h1>

<div class = "predict_price">
<p>合計金額：</p>
<p><%= number_to_currency(@predict_price, unit: "¥", precision: 0) %></p>
</div>

<table class ="table mt-5 mb-5">
  <thead>
    <tr>
      <th>商品名</th>
      <th>金額</th>
      <th>評価</th>
    </tr>
  </thead>
  <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td> 
        <td><%= number_to_currency(product.price, unit: "¥", precision: 0) %></td>  
        <td class = "star-eva"><%= if product.evaluation == 1
                "★☆☆☆☆"
              elsif product.evaluation == 2
                "★★☆☆☆"
              elsif product.evaluation == 3
                "★★★☆☆"
              elsif product.evaluation == 4
                "★★★★☆"
              else product.evaluation == 5
                "★★★★★"
              end %></td>  
      </tr>
      <% end %>
  </tbody> 
</table>  

app/views/products/show.html.erb
<h1 class="display-4 text-primary">マイリスト詳細</h1>
<table class ="table mt-5 mb-5">
  <thead>
    <tr>
      <th>商品名</th>
      <th>価格</th>
      <th>評価</th>
      <th>更新日時</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @product.name %></td> 
        <td><%= number_to_currency(@product.price, unit: "¥", precision: 0) %></td> 
        <td><%= @product.evaluation %></td>  
        <td><%= l @product.updated_at, format: :short %></td>
      </tr>
  </tbody> 
</table>  